### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by windingwind** [windingwind/zotero-tag#1]
# Zotero-Tag TODO List

## Bugs
- [ ] Bug: Some items' automatic-tag will disappear-2021/01/24

## Features
- [ ] Feature: Manage automatic-tag by group-2021/01/24
- [ ] Feature: Remove tags-2021/01/24
- [ ] Feature: Manage tag color-2021/01/24-Desargues(cc98)

**Comment by BaoxueLi** [comment]
Hello, thank you very much for making such a useful plugin.
The current situation is that after right-clicking on the document in Zotero, the option to update the label will appear. But this updated label is directly set as an unread label. Because the purpose of this plug-in is to distinguish between read and unread documents, my little suggestion is to let users choose to update to "read" or "unread" when updating the label.
